version: "3"

services:
  frontend:
    build: .
    ports:
      - "80:80"
  backend:
    image: my-backend-image
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgres://user:password@database:5432/mydatabase
