export const resumeInitial = {
    first_name:'',
    last_name:'',
    avatar:'',
    emails:[''],
    phones:[''],
    birth_date:'',
    resume_title:'',
    country:'',
    city:'',
    sex:'',
    self_description:'',
    educations: [
        {
            title:'',
            institution:'',
            country:'',
            city:'',
            description:'',
            start_date:'',
            end_date:''
        }
    ],
    experiences:[
        {
            position:'',
            employer:'',
            country:'',
            //internship, full, minor, major
            type:'',
            city:'',
            description:'',
            start_date:'',
            end_date:''
        }
    ],
    courses:[
        {
            title:'',
            institution:'',
            country:'',
            city:'',
            description:'',
            start_date:'',
            end_date:''
        }
    ],
    skills:[
        {
            title:'',
            //1 to 10 
            level:''
        }
    ],
    languages:[
        {
            language:'',
            //1 to 10 
            level:''
        }
    ],
    hobbies:[''],
    recommendations:[
        {
            title:'',
            employer:'',
            email:'',
            phone:'',
            description:'',
            country:'',
            city:''           
        }
    ],
    qualities:[''],
    certificates:[
        {
            title:'',
            img:''
        }
    ],
    other:[
        {
            title:'',
            description:''
        }
    ]
}